### ISSUE TITLE
cli create-vpc-endpoint uses only us-east-1

### ISSUE THREAD

**Issue by se-achiu** [lambci/cmda#6]
BTW. nice piece of work you got.  This is not a issue, perhaps a feature request to have CLI create-vpc-endpoint to allowed specifying the AWS region.

**Comment by mhart** [comment]
Can you explain a little more? The client doesn't specify a region, so it should use whichever region you have configured for your AWS setup:

https://github.com/lambci/cmda/blob/d725bdbef994effbfcd234b92425d6c148a3cf5e/cli/actions.js#L157

**Comment by se-achiu** [comment]
The ServiceName in this line: https://github.com/lambci/cmda/blob/d725bdbef994effbfcd234b92425d6c148a3cf5e/cli/actions.js#L195 was using com.amazonaws.us-east-1.s3.

**Comment by mhart** [comment]
Ah, you're right. I should configure that to use the same region 👍

**Comment by mhart** [comment]
Should be fixed in v1.2.0
